#:-------------------------------------------------------------------------------
#: FONT
#:-------------------------------------------------------------------------------

# MonoLisa {{{

font_family                     MonoLisa Light
italic_font                     MonoLisa Medium Italic
bold_font                       MonoLisa Bold
bold_italic_font                MonoLisa Bold Italic
adjust_line_height 134%
adjust_column_width 98%
font_size 14.0
macos_thicken_font 0.05

# }}}
# Iosevka {{{

# font_family                   Iosevka Term Regular
# bold_font                     Iosevka Term Bold
# italic_font                   Iosevka Term Italic
# bold_italic_font              Iosevka Term Bold Italic
# adjust_line_height 135%
# adjust_column_width 100%
# font_size 12.0
# macos_thicken_font 0.00

# }}}
# Cartograph {{{

# font_family                   Cartograph CF Light
# italic_font                   Cartograph CF Demi Bold Italic
# bold_font                     Cartograph CF Bold
# bold_italic_font              Cartograph CF Bold Italic
# adjust_line_height 135%
# adjust_column_width 100%
# font_size 12.0
# macos_thicken_font 0.00

# }}}
# PragmataPro {{{

# font_family                   PragmataPro Mono Liga Regular
# italic_font                   PragmataPro Mono Liga Italic
# bold_font                     PragmataPro Mono Liga Bold
# bold_italic_font              PragmataPro Mono Liga Bold Italic
# adjust_line_height 150%
# adjust_column_width 105%
# font_size 14.0
# macos_thicken_font 0

# }}}

# vim:fileencoding=utf-8:fdm=marker
