theme = "tokyonight_custom"

[editor]
bufferline = "always"
line-number = "relative"
color-modes = true
auto-save = true
auto-format = true
cursorline = true
scroll-lines = 2
mouse = true
auto-pairs = true
rulers = [81]

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "separator"]
center = ["diagnostics"]
right = ["separator", "position", "file-encoding", "separator", "file-line-ending", "separator", "file-type"]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true
git-global = true
git-ignore = true
parents = true

[editor.indent-guides]
render = true
character = "▏" # "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[keys.normal]
# Key mappings
'space'.c.o = ":config-open"
'space'.c.r = ":config-reload"

C-s = ":w"
C-q = ":buffer-close"
C-r = ":reload-all"

# muscle memory (instead of home and end)
"0" = "goto_line_start"
"$" = "goto_line_end"

# add to jumplist
C-z = "save_selection"

# navigate buffers
tab = ":buffer-next"
S-tab = ":buffer-previous"

H = 'extend_char_left'
J = 'extend_line_down'
K = 'extend_line_up'
L = 'extend_char_right'

X = ['extend_to_line_bounds', 'ensure_selections_forward', 'flip_selections']

# like unimpaired
'['.tab = ':set indent-guides.render false'
']'.tab = ':set indent-guides.render true'
'['.r = ':set rulers []'
']'.r = ':set rulers [81]'

[keys.normal.";"]
b = ":sh helix-wezterm.sh blame"
c = ":sh helix-wezterm.sh check"
e = ":sh helix-wezterm.sh explorer"
f = ":sh helix-wezterm.sh fzf"
g = ":sh helix-wezterm.sh lazygit"
o = ":sh helix-wezterm.sh open"
r = ":sh helix-wezterm.sh run"
s = ":sh helix-wezterm.sh test_single"
t = ":sh helix-wezterm.sh test_all"

