theme = "catppuccin_mocha"

[editor]
bufferline = "always"
line-number = "relative"
color-modes = true
auto-save = true
auto-format = true
cursorline = true
scroll-lines = 2
mouse = true
auto-pairs = true
rulers = [81]
end-of-line-diagnostics = "hint"

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.statusline]
left = ["mode", "spinner", "file-name", "separator"]
center = ["diagnostics"]
right = ["separator", "position", "file-encoding", "separator", "file-line-ending", "separator", "file-type"]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.file-picker]
hidden = true
git-global = true
git-ignore = true
parents = true

[editor.indent-guides]
render = true
character = "▏" # "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
# Key mappings
'space'.c.o = ":config-open"
'space'.c.r = ":config-reload"

C-s = ":w"
C-q = ":buffer-close"
C-r = ":reload-all"

# muscle memory (instead of home and end)
"0" = "goto_line_start"
"$" = "goto_line_end"

# add to jumplist
C-z = "save_selection"

# navigate buffers
tab = ":buffer-next"
S-tab = ":buffer-previous"

H = 'extend_char_left'
J = 'extend_line_down'
K = 'extend_line_up'
L = 'extend_char_right'

X = ['extend_to_line_bounds', 'ensure_selections_forward', 'flip_selections']

# like unimpaired
'['.tab = ':set indent-guides.render false'
']'.tab = ':set indent-guides.render true'
'['.r = ':set rulers []'
']'.r = ':set rulers [81]'
'['.w = ':toggle soft-wrap.enable'
']'.w = ':toggle soft-wrap.enable'
