#!/usr/bin/env sh

# Automatically load scripting addition on startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ====== Variables =============================

padding="12"
gap="12"

normal_border_color="4C566A"
focused_border_color="88C0D0"
preselect_border_color="8FBCBB"

# ====== Tiling settings =======================

yabai -m config layout                      bsp

yabai -m config top_padding                 "${padding}"
yabai -m config bottom_padding              "${padding}"
yabai -m config left_padding                "${padding}"
yabai -m config right_padding               "${padding}"
yabai -m config window_gap                  "${gap}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config window_opacity              off
yabai -m config window_topmost              on

yabai -m config window_shadow               off

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       1.0
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                off

# ====== Border settings =======================

# Add spacing for external bar
# yabai -m config external_bar all:26:0

yabai -m config window_border               off
yabai -m config window_border_width         0
yabai -m config active_window_border_color  "0xE0${focused_border_color}"
yabai -m config insert_window_border_color  "0xE0${preselect_border_color}"
yabai -m config normal_window_border_color  "0x00${normal_border_color}"

# ====== Spaces =======================

yabai -m space 1 --label "Primary"
yabai -m space 2 --label "Comms"
yabai -m space 3 --label "Tools"
yabai -m space 4 --label "Media"
yabai -m space 5 --label "Social"

yabai -m config --space 2 layout float

# ====== Rules =========================

# Float these apps
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="Digital Color Meter" manage=off
yabai -m rule --add app="Creative Cloud" manage=off
yabai -m rule --add app="GPG Keychain" manage=off
yabai -m rule --add app="Messages" manage=off
yabai -m rule --add app="Signal" manage=off

# Social
# yabai -m rule --add app="Discord" space=5
# yabai -m rule --add app="Messages" space=5
# yabai -m rule --add app="Signal" space=5
# yabai -m rule --add app="MailMate" space=5

echo "yabai configuration loaded.."

#END
