name = "Ferdinand Salis-Samaden"
downloads-dir = "/home/ferdinand/Downloads/email"
signature = "Regards,"

[gmail]
default = true
email = "$EMAIL"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "ferdinandsalis@gmail.com"
imap-passwd-cmd = "op get item gmail.himalaya --fields password --format csv"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "ferdinandsalis@gmail.com"
smtp-passwd-cmd = "op get item gmail.himalaya --fields password --format csv"
