# Atuin configuration

## Database configuration
db_path = "~/.local/share/atuin/history.db"
key_path = "~/.local/share/atuin/key"
session_path = "~/.local/share/atuin/session"

## Search configuration
search_mode = "fuzzy"
filter_mode = "global"
filter_mode_shell_up_key_binding = "session"
style = "compact"
show_preview = true
show_help = true
exit_mode = "return-original"
inline_height = 20
invert = false
secrets_filter = true
workspaces = false

## History configuration
history_filter = []
max_preview_height = 4
update_check = true

## Sync configuration (optional)
# sync_address = "https://api.atuin.sh"
# sync_frequency = "10m"

## Shell integration
enter_accept = true