# Taps
tap "aws/tap"
tap "candid82/brew"
tap "cmacrae/formulae"
tap "craciuncezar/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "khanhas/tap"

#: Core CLI Tools
brew "automake"
brew "fish"
brew "mise"
brew "aws/tap/aws-sam-cli"
brew "awscli"
brew "bat"
brew "cmake"
brew "coreutils"
brew "curl"
brew "duti"
brew "eza"
brew "fd"
brew "fswatch"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "git-delta"
brew "git-flow"
brew "gnupg"
brew "go"
brew "btop"
brew "hub"
brew "jq"
brew "yq"
brew "lazydocker"
brew "lazygit"
brew "bottom"
brew "dust"
brew "procs"
brew "zoxide"
brew "zellij"
brew "httpie"
brew "jless"
brew "glow"
brew "openssl@3"
brew "readline"
brew "ripgrep"
brew "rsync"
brew "rustup-init"
brew "sqlite"
brew "todo-txt"
brew "tree"
brew "wget"

#: Critical System Tools
cask "1password"
cask "1password-cli"
cask "karabiner-elements"
cask "raycast"

#: Development Environment
cask "ghostty"
cask "visual-studio-code"
cask "postico"
cask "insomnia"

#: Work & Communication
cask "slack"
cask "mailmate"
cask "figma"
cask "discord"
cask "signal"

#: Productivity & Utilities
cask "maccy"
cask "jordanbaird-ice"
cask "spotify"
cask "dropbox"
cask "kap"
cask "numi"

#: Security
cask "lulu"

#: Browsers
cask "firefox"
cask "google-chrome"

#: Fonts
cask "font-alegreya"
cask "font-alegreya-sans"
cask "font-alegreya-sans-sc"
cask "font-alegreya-sc"
cask "font-blex-mono-nerd-font"
cask "font-hasklug-nerd-font"
cask "font-iosevka"
cask "font-victor-mono"
cask "font-hack-nerd-font"

#: Mac App Store
brew "mas"
mas "Table Tool", id: 1122008420
mas "Vimari", id: 1480933944