return function()
  require('substitute').setup()
  fss.nnoremap('S', function()
    require('substitute').operator()
  end)
  fss.xnoremap('S', function()
    require('substitute').visual()
  end)
  fss.nnoremap('X', function()
    require('substitute.exchange').operator()
  end)
  fss.xnoremap('X', function()
    require('substitute.exchange').visual()
  end)
  fss.nnoremap('Xc', function()
    require('substitute.exchange').cancel()
  end)
end
