-- Styles

local everforest = {
  fg = '#d3c6aa',
  red = '#e67e80',
  orange = '#e69875',
  yellow = '#dbbc7f',
  green = '#a7c080',
  aqua = '#83c092',
  blue = '#7fbbb3',
  purple = '#d699b6',
  grey0 = '#7a8478',
  grey1 = '#859289',
  grey2 = '#9da9a0',
  white = '#d3c6aa',
  bg = '#2b3339',
  bg0 = '#2b3339',
  bg1 = '#323c41',
  bg2 = '#3a454a',
  bg3 = '#445055',
  bg4 = '#4c555b',
  bg5 = '#53605c',
  bg_visual = '#503946',
  bg_red = '#4e3e43',
  bg_green = '#404d44',
  bg_blue = '#394f5a',
  bg_yellow = '#4a4940',
}

local icons = {
  lsp = {
    error = ' ',
    warn = ' ',
    hint = ' ',
    info = ' ',
  },
  git = {
    logo = '',
    add = '', -- '',
    mod = '', -- '',
    remove = '', --
    ignore = '',
    rename = '',
    diff = '',
    repo = '',
  },
  documents = {
    file = '',
    files = '',
    folder = '',
    open_folder = '',
  },
  type = {
    array = '',
    number = '',
    object = '',
  },
  misc = {
    up = '⇡',
    down = '⇣',
    line = '', -- ℓ
    column = '',
    indent = 'Ξ',
    tab = '⇥',
    bug = '', -- 'ﴫ'
    question = '',
    lock = '',
    circle = '',
    project = '',
    dashboard = '',
    history = '',
    comment = '',
    robot = 'ﮧ',
    lightbulb = '',
    search = '',
    code = '',
    telescope = '',
    gear = '',
    package = '',
    list = '',
    sign_in = '',
    check = '',
    fire = '',
    note = '',
    bookmark = '',
    pencil = '',
    tools = '',
    chevron_right = '',
    double_chevron_right = '»',
    table = '',
    calendar = '',
    block = '▌',
  },
}

local lsp = {
  colors = {
    error = everforest.red,
    warn = everforest.orange,
    hint = everforest.yellow,
    info = everforest.teal,
  },
  highlights = {
    Text = 'String',
    Method = 'TSMethod',
    Function = 'Function',
    Constructor = 'TSConstructor',
    Field = 'TSField',
    Variable = 'TSVariable',
    Class = 'TSFunction',
    Interface = 'Constant',
    Module = 'Include',
    Property = 'TSProperty',
    Unit = 'Constant',
    Value = 'TSVariable',
    Enum = 'Type',
    Keyword = 'TSKeyword',
    File = 'Directory',
    Reference = 'PreProc',
    Constant = 'Constant',
    Struct = 'Type',
    Snippet = 'Label',
    Event = 'TSVariable',
    Operator = 'Operator',
    TypeParameter = 'Type',
    Namespace = 'TSNamespace',
    Package = 'Include',
    String = 'String',
    Number = 'Number',
    Boolean = 'Boolean',
    Array = 'StorageClass',
    Object = 'Type',
    Key = 'TSField',
    Null = 'ErrorMsg',
    EnumMember = 'TSField',
  },
  kinds = {
    nerdfonts = {
      Text = '',
      Method = '',
      Function = '',
      Constructor = '',
      Field = '', -- '',
      Variable = '', -- '',
      Class = '', -- '',
      Interface = '',
      Module = '',
      Property = 'ﰠ',
      Unit = '塞',
      Value = '',
      Enum = '',
      Keyword = '', -- '',
      Snippet = '', -- '', '',
      Color = '',
      File = '',
      Reference = '', -- '',
      Folder = '',
      EnumMember = '',
      Constant = '', -- '',
      Struct = '', -- 'פּ',
      Event = '',
      Operator = '',
      TypeParameter = '',
      Namespace = '?',
      Package = '?',
      String = '?',
      Number = '?',
      Boolean = '?',
      Array = '?',
      Object = '?',
      Key = '?',
      Null = '?',
    },
  },
}

fss.style = {
  palette = everforest,
  icons = icons,
  lsp = lsp,
  float = {
    blend = 5,
  },
  border = {
    line = {
      { '🭽' },
      { '▔' },
      { '🭾' },
      { '▕' },
      { '🭿' },
      { '▁' },
      { '🭼' },
      { '▏' },
    },
    rectangle = { '┌', '─', '┐', '│', '┘', '─', '└', '│' },
  },
}

----------------------------------------------------------------------------------------------------
-- Global style settings
----------------------------------------------------------------------------------------------------
-- Some styles can be tweaked here to apply globally i.e. by setting the current value for that style

fss.style.current = {
  border = fss.style.border.line,
  lsp_icons = fss.style.lsp.kinds.nerdfonts,
  palette = everforest,
}
