#!/usr/bin/env sh

spacebar -m config position             top
spacebar -m config height               26
spacebar -m config background_color     0xFF1F2335
spacebar -m config foreground_color     0xFFc0caf5
spacebar -m config space_icon_color     0xff458588
spacebar -m config power_icon_color     0xffcd950c
spacebar -m config battery_icon_color   0xffd75f5f
spacebar -m config dnd_icon_color       0xffa8a8a8
spacebar -m config clock_icon_color     0xffa8a8a8
spacebar -m config dnd_icon             
spacebar -m config text_font            "Hasklug Nerd Font:Regular:14.0"
spacebar -m config icon_font            "Hasklug Nerd Font:Regular:14.0"
spacebar -m config space_icon_strip     1 2 3 4 5 6
