#!/usr/bin/zsh
#=======================================================================
# ENV VARIABLES
#=======================================================================

export DOTFILES=$HOME/.dotfiles
export PROJECTS_DIR=$HOME/Desktop/Personal/Code
export WORK_DIR=$HOME/Desktop/Work

if which yarn >/dev/null; then
  path+=("$(yarn global bin)")
fi

path+=(
  "/usr/local/bin"
  "$HOME/.npm/bin"
  "$HOME/.local/bin"
)

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export MANPATH="/usr/local/man:$MANPATH"

if [ -f "$HOME/.environment.secret.sh" ]; then
  source $HOME/.environment.secret.sh
fi

# Compilation flags
# export ARCHFLAGS="-arch arm64"

# preferred editor for local and remote sessions
if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
    export VISUAL="nvr -cc split --remote-wait +'set bufhidden=wipe'"
    export EDITOR="nvr -cc split --remote-wait +'set bufhidden=wipe'"
else
    export VISUAL="nvim"
    export EDITOR="nvim"
fi

export USE_EDITOR=$EDITOR

export SSH_KEY_PATH="~/.ssh/rsa_id"

export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=241'

if ! type "$bat" > /dev/null; then
  export BAT_THEME="TwoDark"
fi

# Fuzzy Finder
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'
export FZF_DEFAULT_OPTS="--history=$HOME/.fzf_history"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_TMUX=0
