#!/usr/bin/zsh
#=======================================================================
# ENV VARIABLES
#=======================================================================

export DOTFILES=$HOME/.dotfiles
export PROJECTS_DIR=$HOME/Desktop/Personal/Code
export WORK_DIR=$HOME/Desktop/Work

if which yarn >/dev/null; then
  path+=("$(yarn global bin)")
fi

path+=(
  "/usr/local/bin"
  "$HOME/.npm/bin"
  "$HOME/.local/bin"
  "$HOME/.cargo/bin"
)

export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="/usr/local/opt/terraform@0.12/bin:$PATH"

# Prefer US English and use UTF-8.
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export MANPATH="/usr/local/man:$MANPATH"
if which nvim >/dev/null; then
  export MANPAGER='nvim +Man!'
fi

if [ -f "$HOME/.environment.secret.sh" ]; then
  source $HOME/.environment.secret.sh
fi

# Add LUA_PATH to the environment ensuring the lua version is set since
# luarocks from homebrew uses lua 5.4 by default so would otherwise add the
# wrong path
if which luarocks >/dev/null; then
  eval "$(luarocks --lua-version=5.1 path)"
fi

# Compilation flags
# export ARCHFLAGS="-arch arm64"

# preferred editor for local and remote sessions
if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
  export VISUAL="nvr -cc split --remote-wait +'set bufhidden=wipe'"
  export EDITOR="nvr -cc split --remote-wait +'set bufhidden=wipe'"
else
  export VISUAL="nvim"
  export EDITOR="nvim"
fi

export USE_EDITOR=$EDITOR

export SSH_KEY_PATH="~/.ssh/rsa_id"

export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=241'

if ! type "$bat" > /dev/null; then
  export BAT_THEME="ansi"
fi

# Fuzzy Finder
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'
export FZF_DEFAULT_OPTS="--history=$HOME/.fzf_history"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_TMUX=0
